export default [
  'Around The House',
  'Before After',
  'Character',
  'Characters',
  'College Life',
  'Crossword',
  'Event',
  'Events',
  'Fictional Character',
  'Fictional Characters',
  'Food Drink',
  'Fun Games',
  'Headline',
  'In The Kitchen',
  'Landmark',
  'Landmarks',
  'Living Thing',
  'Living Things',
  'Movie Quote',
  'Occupation',
  'Occupations',
  'On The Map',
  'People',
  'Person',
  'Phrase',
  'Phrases',
  'Place',
  'Places',
  'Proper Name',
  'Proper Names',
  'Quotation',
  'Rhyme Time',
  'Same Letter',
  'Same Name',
  'Show Biz',
  'Slogan',
  'Song Lyrics',
  'Song Artist',
  'Star Role',
  'Thing',
  'Things',
  'Title',
  'Titles',
  'Tv Quote',
  'What Are You Doing',
]
